name: doffrl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - pytorch=1.8.1
  - torchvision
  - torchaudio
  - cudatoolkit=10.1
  - tensorflow=2.4.1
  - jupyter
  - pip:
      - gym
      - gym-minigrid
      - tensorboard